Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2020-08, with the labels that each got.

#29 Moved module description to DescriptionAttribute of module
  docs/tutorials/ServerModule/ServerModule.md
  src/DependentTestModule/ModuleController/ModuleConsole.cs
  src/DependentTestModule/ModuleController/ModuleController.cs
  src/Moryx.Runtime.Kernel/RunMode/Command/Commands/ConsoleCommand.cs
  src/Moryx.Runtime.Maintenance/ModuleController/ModuleConsole.cs
  src/Moryx.Runtime.Maintenance/ModuleController/ModuleController.cs
  src/Moryx.Runtime/Modules/IServerModuleConsole.cs
  src/TestModule/ModuleController/ModuleConsole.cs
  src/TestModule/ModuleController/ModuleController.cs
Labels: enhancement

#32 Restored implementation of GetEntity for UnitOfWork
  src/Moryx.Model/Extensions/UnitOfWorkExtensions.cs
  src/Moryx.Model/Repositories/UnitOfWorkFactory.cs
Labels: bug

#33 Execute ModelSetups with IUnitOfWork instead of DbContext
  docs/tutorials/DataModel/ModelSetups.md
  src/Moryx.Model.InMemory/InMemoryDbContextManager.cs
  src/Moryx.Model.InMemory/InMemoryUnitOfWorkFactory.cs
  src/Moryx.Model.InMemory/Moryx.Model.InMemory.csproj
  src/Moryx.Model.PostgreSQL/NpgsqlModelConfigurator.cs
  src/Moryx.Model/Configuration/ModelConfiguratorBase.cs
  src/Moryx.Model/Configuration/NullModelConfigurator.cs
  src/Moryx.Model/DbContextManager.cs
  src/Moryx.Model/EntityIdListener.cs
  src/Moryx.Model/Extensions/DbContextExtensions.cs
  src/Moryx.Model/IDbContextManager.cs
  src/Moryx.Model/IModelConfigurator.cs
  src/Moryx.Model/IModelSetup.cs
  src/Moryx.Model/IModelSetupExecutor.cs
  src/Moryx.Model/ModelSetupExecutor.cs
  src/Moryx.Model/Moryx.Model.csproj
  src/Moryx.Model/MoryxDbContext.cs
  src/Moryx.Model/Repositories/UnitOfWorkFactory.cs
  src/Moryx.Runtime.DbUpdate/DbUpdateRunMode.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/DatabaseMaintenance.cs
  src/Moryx.Runtime.SmokeTest/SmokeTest.cs
  src/Moryx.TestTools.Test.Model/Setups/AnySetup.cs
Labels: data-model, enhancement

#39 Add option for full name to possible types
  src/Moryx/Serialization/PossibleValues/PossibleTypesAttribute.cs
  src/Tests/Moryx.Tests/Serialization/PossibleValues/PossibleValuesAttributeTests.cs
Labels: enhancement
