Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2020-11, with the labels that each got.

#70 Clean up of logging in kernel
  src/Moryx.Runtime.Kernel/Logging/CommonLoggingLogTarget.cs
  src/Moryx.Runtime.Kernel/Logging/LogTarget.cs
  src/Moryx.Runtime.Kernel/Logging/LoggingConfig.cs
  src/Moryx.Runtime.Kernel/Logging/ServerLoggerManagement.cs
  src/Moryx/Logging/ILogTarget.cs
  src/Tests/Moryx.Tests/Logging/TestLoggerManagement.cs
Labels: enhancement

#68 Use SourceLink to patch pdbs and provide snupkg
  .build/BuildToolkit.ps1
  .build/Common.props
  .github/workflows/build-and-test.yml
  Build.ps1
  Directory.Build.targets
  Directory.build.props
  src/Moryx.Communication.Serial/Moryx.Communication.Serial.csproj
  src/Moryx.Container/Moryx.Container.csproj
  src/Moryx.Model.InMemory/Moryx.Model.InMemory.csproj
  src/Moryx.Model.PostgreSQL/Moryx.Model.PostgreSQL.csproj
  src/Moryx.Model/Moryx.Model.csproj
  src/Moryx.Runtime.DbUpdate/Moryx.Runtime.DbUpdate.csproj
  src/Moryx.Runtime.Kernel/Moryx.Runtime.Kernel.csproj
  src/Moryx.Runtime.Maintenance/Moryx.Runtime.Maintenance.csproj
  src/Moryx.Runtime.SmokeTest/Moryx.Runtime.SmokeTest.csproj
  src/Moryx.Runtime.Wcf/Moryx.Runtime.Wcf.csproj
  src/Moryx.Runtime.WinService/Moryx.Runtime.WinService.csproj
  src/Moryx.Runtime/Moryx.Runtime.csproj
  src/Moryx.TestTools.SystemTest/Moryx.TestTools.SystemTest.csproj
  src/Moryx.TestTools.UnitTest/Moryx.TestTools.UnitTest.csproj
  src/Moryx.TestTools.UnitTest/app.config
  src/Moryx.Tools.Wcf/Moryx.Tools.Wcf.csproj
  src/Moryx/Moryx.csproj
Labels: enhancement

#71 Symbol packages (snupkg) must be published by v3 nuget api
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  src/Moryx.Communication.Serial/Moryx.Communication.Serial.csproj
  src/Moryx.Container/Moryx.Container.csproj
  src/Moryx.Model.InMemory/Moryx.Model.InMemory.csproj
  src/Moryx.Model.PostgreSQL/Moryx.Model.PostgreSQL.csproj
  src/Moryx.Model/Moryx.Model.csproj
  src/Moryx.Runtime.DbUpdate/Moryx.Runtime.DbUpdate.csproj
  src/Moryx.Runtime.Kernel/Moryx.Runtime.Kernel.csproj
  src/Moryx.Runtime.Maintenance/Moryx.Runtime.Maintenance.csproj
  src/Moryx.Runtime.SmokeTest/Moryx.Runtime.SmokeTest.csproj
  src/Moryx.Runtime.Wcf/Moryx.Runtime.Wcf.csproj
  src/Moryx.Runtime.WinService/Moryx.Runtime.WinService.csproj
  src/Moryx.Runtime/Moryx.Runtime.csproj
  src/Moryx.TestTools.SystemTest/Moryx.TestTools.SystemTest.csproj
  src/Moryx.TestTools.UnitTest/Moryx.TestTools.UnitTest.csproj
  src/Moryx.Tools.Wcf/Moryx.Tools.Wcf.csproj
  src/Moryx/Moryx.csproj
Labels: bug

#73 Several fixes after beta test
  src/Moryx.Model.PostgreSQL/NpgsqlModelConfigurator.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/DatabaseMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/AssemblyModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/ModuleMaintenance.cs
Labels: bug, enhancement

#76 Fix prototype issues for primitive collections
  src/Moryx/Configuration/PossibleValuesSerialization.cs
  src/Moryx/Serialization/DefaultSerialization.cs
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
  src/Tests/Moryx.Tests/Serialization/ListDummy.cs
  src/Tests/Moryx.Tests/Serialization/SerializationTests.cs
Labels: bug

#77 Fixed cors preflight behavior
  src/Moryx.Runtime.Wcf/CorsBehaviorAttribute.cs
Labels: bug

#78 Add missing validation to prototypes
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
Labels: bug

#79 Doc cleanup before release
  docs/articles/Platform/BinaryConnection.md
  docs/articles/Platform/Bindings.md
  docs/articles/Platform/Serialization/EntryConvert.md
  docs/articles/Platform/Serialization/EntryFormat.md
  docs/articles/Platform/Serialization/PossibleValues.md
Labels: documentation

#80 Fix CORS for GET again
  src/Moryx.Runtime.Wcf/CorsBehaviorAttribute.cs
Labels: bug

#81 Prepared workflow for release and push to NuGet
  .github/workflows/build-and-test.yml
Labels: enhancement

#83 Usage of dotnet instead of msbuild and .net5.0 tfm
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  Directory.build.props
  README.md
  src/Moryx.Communication.Serial/Moryx.Communication.Serial.csproj
  src/Moryx.Container/Moryx.Container.csproj
  src/Moryx.Model.InMemory/Moryx.Model.InMemory.csproj
  src/Moryx.Model.PostgreSQL/Moryx.Model.PostgreSQL.csproj
  src/Moryx.Model/Moryx.Model.csproj
  src/Moryx.Runtime.DbUpdate/Moryx.Runtime.DbUpdate.csproj
  src/Moryx.Runtime.Kernel/Moryx.Runtime.Kernel.csproj
  src/Moryx.Runtime.SmokeTest/Moryx.Runtime.SmokeTest.csproj
  src/Moryx.Runtime/Moryx.Runtime.csproj
  src/Moryx.TestTools.Test.Model/Moryx.TestTools.Test.Model.csproj
  src/Moryx.TestTools.UnitTest/Moryx.TestTools.UnitTest.csproj
  src/Moryx/Moryx.csproj
  src/StartProject.Core/StartProject.Core.csproj
  src/Tests/Moryx.Communication.Sockets.IntegrationTests/Moryx.Communication.Sockets.IntegrationTests.csproj
  src/Tests/Moryx.Container.TestPlugin/Moryx.Container.TestPlugin.csproj
  src/Tests/Moryx.Container.TestRootPlugin/Moryx.Container.TestRootPlugin.csproj
  src/Tests/Moryx.Container.TestTools/Moryx.Container.TestTools.csproj
  src/Tests/Moryx.Container.Tests/Moryx.Container.Tests.csproj
  src/Tests/Moryx.Model.Tests/Moryx.Model.Tests.csproj
  src/Tests/Moryx.Runtime.Kernel.Tests/Moryx.Runtime.Kernel.Tests.csproj
  src/Tests/Moryx.Runtime.Kernel.Tests/app.config
  src/Tests/Moryx.Runtime.SystemTests/app.config
  src/Tests/Moryx.Runtime.Tests/Moryx.Runtime.Tests.csproj
  src/Tests/Moryx.Runtime.Tests/app.config
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
  src/Tests/Moryx.Workflows.Benchmark/Moryx.Workflows.Benchmark.csproj
Labels: enhancement

#86 WIP: Improve readonly behavior in EntryConvert
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
  src/Tests/Moryx.Tests/Serialization/ListDummy.cs
  src/Tests/Moryx.Tests/Serialization/SerializationTests.cs
Labels: bug
