Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2020-09, with the labels that each got.

#40 Fix dictionary detection in EntryConvert
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
Labels: bug

#41 Support encoding root collections in EntryConvert
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
  src/Tests/Moryx.Tests/Serialization/SerializationTests.cs
Labels: bug

#36 Rework test execution to support .NET Core tests
  .build/BuildToolkit.ps1
  src/Moryx.TestTools.SystemTest/Clients/LogMaintenanceWebClient.cs
  src/Moryx.TestTools.SystemTest/Clients/TestWebClientBase.cs
  src/Moryx.TestTools.SystemTest/HeartOfGoldController.cs
  src/Tests/Moryx.Runtime.SystemTests/BasicConfigTests.cs
  src/Tests/Moryx.Runtime.SystemTests/BasicTests.cs
  src/Tests/Moryx.Runtime.SystemTests/DatabaseTests.cs
  src/Tests/Moryx.Runtime.SystemTests/HogHelper.cs
  src/Tests/Moryx.Runtime.SystemTests/LifeCycleTests.cs
  src/Tests/Moryx.Runtime.SystemTests/LoggingTests.cs
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
  src/Tests/Moryx.Tests/Serialization/EntryToModelConverterTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/ClientFactoryTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/VersionServiceTests.cs
Labels: bug, enhancement

#42 Exclude modules with missing (transient) dependencies
  src/Moryx.Runtime.Kernel/Modules/ComponentContracts/IModuleDependencyManager.cs
  src/Moryx.Runtime.Kernel/Modules/ComponentContracts/IModuleInitializer.cs
  src/Moryx.Runtime.Kernel/Modules/ComponentContracts/IModuleManagerComponent.cs
  src/Moryx.Runtime.Kernel/Modules/ComponentContracts/IModuleStarter.cs
  src/Moryx.Runtime.Kernel/Modules/ComponentContracts/IModuleStopper.cs
  src/Moryx.Runtime.Kernel/Modules/Components/DependencyEvaluation.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleDependencyManager.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleDependencyTree.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleInitializer.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleManagerComponent.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleStarter.cs
  src/Moryx.Runtime.Kernel/Modules/Components/ModuleStopper.cs
  src/Moryx.Runtime.Kernel/Modules/ModuleManager.cs
  src/Moryx.Runtime.Kernel/RunMode/Command/Commands/PrintCommand.cs
  src/Moryx.Runtime.Kernel/RunMode/Command/DeveloperConsole.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/DependencyEvaluation.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/ModuleMaintenance.cs
  src/Moryx.Runtime/Modules/Management/IDependencyTreeValidation.cs
  src/Moryx.Runtime/Modules/Management/IModuleDependencyTree.cs
  src/Moryx.Runtime/Modules/Management/IModuleManager.cs
  src/Moryx.Runtime/Modules/States/FailureState.cs
  src/Moryx.Runtime/Modules/States/InitializingState.cs
  src/Moryx.Runtime/Modules/States/ReadyState.cs
  src/Moryx.Runtime/Modules/States/RunningState.cs
  src/Moryx.Runtime/Modules/States/ServerModuleStateBase.cs
  src/Moryx.Runtime/Modules/States/StartingState.cs
  src/Moryx.Runtime/Modules/States/StoppedState.cs
  src/Moryx.Runtime/Modules/States/StoppingState.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleManagerTests.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/IFacadeC.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/ModuleADependend.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/ModuleBUsingA.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/ModuleC.cs
Labels: bug, enhancement

#43 Fix spelling and include RangeAttribute in validation
  src/Moryx/Serialization/DefaultSerialization.cs
  src/Moryx/Serialization/EntryConvert/EntryValidation.cs
Labels: enhancement

#46 Added support for beta and rc version tags to BuildToolkit
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  .vscode/launch.json
  Build.ps1
Labels: enhancement
