Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2020-10, with the labels that each got.

#48 Fix and stabilize test execution
  src/Moryx/Collections/DelayQueue/DelayQueue.cs
  src/Moryx/Collections/DelayQueue/States/IDelayQueueContext.cs
  src/Moryx/Collections/DelayQueue/States/QueuePendingState.cs
  src/Tests/Moryx.Communication.Sockets.IntegrationTests/CommunicationSocketsTestsBase.cs
  src/Tests/Moryx.Communication.Sockets.IntegrationTests/HeaderProtocol/HeaderedCommunicationSocketTests.cs
Labels: bug

#51 Removed BundleAttribute and minor improvements to workflow
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  src/DependentTestModule/Properties/AssemblyInfo.cs
  src/Moryx.Runtime.Kernel/KernelBundleAttribute.cs
  src/Moryx.Runtime.Kernel/Moryx.Runtime.Kernel.csproj
  src/Moryx.Runtime.Kernel/Properties/AssemblyInfo.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/AssemblyModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/ModuleMaintenance.cs
  src/Moryx.Runtime.Maintenance/Properties/AssemblyInfo.cs
  src/Moryx.Runtime.SmokeTest/Moryx.Runtime.SmokeTest.csproj
  src/Moryx/Modules/BundleAttribute.cs
  src/TestModule/Properties/AssemblyInfo.cs
Labels: enhancement

#54 Change endpoint service to REST, refactor client factory
  MoryxPlatform.sln
  src/DependentTestModule/Plugins/ISimpleHelloWorldWcfService.cs
  src/DependentTestModule/Plugins/SimpleHelloWorldWcfService.cs
  src/Moryx.Runtime.Maintenance/Plugins/Common/Wcf/ICommonMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/IDatabaseMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/Wcf/ILogMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/IModuleMaintenance.cs
  src/Moryx.Runtime.Wcf/ConfiguredServiceHost.cs
  src/Moryx.Runtime.Wcf/EndpointCollector.cs
  src/Moryx.Runtime.Wcf/IEndpointCollector.cs
  src/Moryx.Runtime.Wcf/VersionService.cs
  src/Moryx.Runtime.Wcf/WcfHostFactory.cs
  src/Moryx.Tools.Wcf/Client/BaseWcfClientFactory.cs
  src/Moryx.Tools.Wcf/Client/BindingFactory.cs
  src/Moryx.Tools.Wcf/Client/ClientConfig.cs
  src/Moryx.Tools.Wcf/Client/Contracts/BindingType.cs
  src/Moryx.Tools.Wcf/Client/Contracts/IClientConfig.cs
  src/Moryx.Tools.Wcf/Client/Contracts/IWcfClientFactory.cs
  src/Moryx.Tools.Wcf/Client/Contracts/WcfClientInfo.cs
  src/Moryx.Tools.Wcf/Client/MonitoredClient.cs
  src/Moryx.Tools.Wcf/Client/VersionService/IVersionServiceManager.cs
  src/Moryx.Tools.Wcf/Client/VersionService/ServiceConfiguration.cs
  src/Moryx.Tools.Wcf/Client/VersionService/VersionServiceManager.cs
  src/Moryx.Tools.Wcf/Properties/AssemblyInfo.cs
  src/Moryx.Tools.Wcf/Service/Contracts/IVersionService.cs
  src/Moryx.Tools.Wcf/Service/Endpoint.cs
  src/Moryx.Tools.Wcf/Service/ServiceEndpoint.cs
  src/Moryx.Tools.Wcf/Service/ServiceVersionAttribute.cs
  src/TestModule/Plugin/HelloWorldWcfService.cs
  src/TestModule/Plugin/IHelloWorldWcfService.cs
  src/Tests/Moryx.Runtime.SystemTests/HogHelper.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/ClientFactoryTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/Connected Services/Logging/ConnectedService.json
  src/Tests/Moryx.Tools.Wcf.SystemTests/Connected Services/Logging/Reference.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/LogMaintenanceClientMock.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/TestWcfClientFactory.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/VersionServiceManagerMock.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/VersionServiceTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/WcfClientFactoryTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/app.config
  src/Tests/Moryx.Tools.Wcf.Tests/Moryx.Tools.Wcf.Tests.csproj
  src/Tests/Moryx.Tools.Wcf.Tests/VersionServiceManagerMock.cs
  src/Tests/Moryx.Tools.Wcf.Tests/app.config
Labels: enhancement

#55 Execute test jobs in parallel
  .github/workflows/build-and-test.yml
  Build.ps1
  src/StartProject/StartProject.csproj
  src/Tests/Moryx.Runtime.SystemTests/HogHelper.cs
Labels: enhancement

#56 Added inheritance support to EntrySerialize
  src/Moryx/Serialization/EntrySerializeSerialization.cs
  src/Tests/Moryx.Tests/Serialization/EntrySerializeDummies.cs
  src/Tests/Moryx.Tests/Serialization/EntrySerializeSerializationTests.cs
Labels: bug

#57 Workfow with uploaded artifacts and generate documentation
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
Labels: enhancement

#58 Provide base class for web http connector
  src/Moryx.Tools.Wcf/Client/BaseWcfClientFactory.cs
  src/Moryx.Tools.Wcf/Client/Connector/WebHttpServiceConnectorBase.cs
  src/Moryx.Tools.Wcf/Client/Contracts/IWcfClientFactory.cs
  src/Moryx.Tools.Wcf/Client/Contracts/WcfClientInfo.cs
  src/Moryx.Tools.Wcf/Client/VersionService/IVersionServiceManager.cs
  src/Moryx.Tools.Wcf/Client/VersionService/VersionServiceManager.cs
  src/Moryx.Tools.Wcf/Moryx.Tools.Wcf.csproj
  src/Tests/Moryx.Tools.Wcf.SystemTests/ClientFactoryTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/VersionServiceManagerMock.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/VersionServiceTests.cs
  src/Tests/Moryx.Tools.Wcf.SystemTests/WcfClientFactoryTests.cs
Labels: bug, enhancement

#60 Improved readability in WebHttpServiceConnectorBase
  src/Moryx.Tools.Wcf/Client/Connector/WebHttpServiceConnectorBase.cs
Labels: enhancement

#64 Provide DeleteAsync<T> in WebHttpServiceConnectorBase
  src/Moryx.Tools.Wcf/Client/Connector/WebHttpServiceConnectorBase.cs
Labels: bug

#66 Create service host by type in addition to generic
  src/Moryx.Runtime.Maintenance/Contracts/IMaintenancePlugin.cs
  src/Moryx.Runtime.Maintenance/Contracts/IMaintenancePluginFactory.cs
  src/Moryx.Runtime.Maintenance/Contracts/MaintenanceModuleConfig.cs
  src/Moryx.Runtime.Maintenance/Contracts/MaintenancePluginBase.cs
  src/Moryx.Runtime.Maintenance/ModuleController/ModuleConfig.cs
  src/Moryx.Runtime.Maintenance/ModuleController/ModuleController.cs
  src/Moryx.Runtime.Maintenance/Moryx.Runtime.Maintenance.csproj.DotSettings
  src/Moryx.Runtime.Maintenance/Plugins/Common/CommonMaintenanceConfig.cs
  src/Moryx.Runtime.Maintenance/Plugins/Common/CommonMaintenancePlugin.cs
  src/Moryx.Runtime.Maintenance/Plugins/Common/Wcf/CommonMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Common/Wcf/ICommonMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/DatabaseConfig.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/DatabasePlugin.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/DatabaseMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/IDatabaseMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Models/BackupModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Models/DataModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Models/DatabaseConfigModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Models/SetupModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Request/ExecuteSetupRequest.cs
  src/Moryx.Runtime.Maintenance/Plugins/Databases/Wcf/Request/RestoreDatabaseRequest.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/ILoggingAppender.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/LoggingAppenderPlugin.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/LoggingMaintenanceConfig.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/Wcf/ILogMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/Wcf/LogMaintenance.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/Wcf/Models/LogMessageModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Logging/Wcf/Models/LoggerModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/ModuleMaintenanceConfig.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/ModuleMaintenancePlugin.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/Config.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/DependencyEvaluation.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/ModuleNotificationType.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/ModuleServerModuleState.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/NotificationModel.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/SerializableException.cs
  src/Moryx.Runtime.Maintenance/Plugins/Modules/Wcf/Models/ServerModuleModel.cs
  src/Moryx.Runtime.Wcf/ConfiguredHostFactory.cs
  src/Moryx.Runtime.Wcf/ConfiguredServiceHost.cs
  src/Moryx.Runtime.Wcf/TypedHostFactory.cs
  src/Moryx.Runtime.Wcf/WcfHostFactory.cs
  src/Moryx.TestTools.SystemTest/Clients/DatabaseMaintenanceWebClient.cs
  src/Moryx.TestTools.SystemTest/Clients/LogMaintenanceWebClient.cs
  src/Moryx.TestTools.SystemTest/Clients/ModuleMaintenanceWebClient.cs
  src/Moryx.TestTools.SystemTest/ModuleConfigurator.cs
  src/Moryx.Tools.Wcf/Service/Contracts/IConfiguredHostFactory.cs
  src/Moryx.Tools.Wcf/Service/Contracts/ITypedHostFactory.cs
  src/Moryx.Tools.Wcf/Service/Contracts/IWcfHostFactory.cs
Labels: enhancement
