Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2021-01, with the labels that each got.

#90 Use s format specifier for crash log timestamp
  src/Moryx/Tools/CrashHandler.cs
Labels: bug

#93 Parse and use configured IPAddress in tcp listener
  src/Moryx/Communication/Sockets/Server/TcpListenerConnection.cs
  src/Moryx/Communication/Sockets/Server/TcpPortListener.cs
  src/Moryx/Communication/Sockets/Server/TcpServer.cs
  src/Tests/Moryx.Tests/Communication/PortMapTests.cs
Labels: bug

#94 Throw exception for invalid IPAddress
  src/Moryx/Communication/Sockets/Server/TcpListenerConnection.cs
Labels: enhancement

#95 Separated Initialize from IConfiguredPlugin into new IConfiguredInitializable
  src/Moryx.Container/ComponentSelectors/ConfigBasedComponentSelector.cs
  src/Moryx.Tools.Wcf/Service/BasicWcfConnectorPlugin.cs
  src/Moryx/Modules/IConfiguredInitializable.cs
  src/Moryx/Modules/IConfiguredPlugin.cs
  src/Moryx/Serialization/PossibleValues/PluginConfigsAttribute.cs
  src/TestModule/Plugin/ITestSubPlugin.cs
Labels: enhancement

#96 Add package tags, fix description typos
  src/Moryx.Communication.Serial/Moryx.Communication.Serial.csproj
  src/Moryx.Container/Moryx.Container.csproj
  src/Moryx.Model.InMemory/Moryx.Model.InMemory.csproj
  src/Moryx.Model.PostgreSQL/Moryx.Model.PostgreSQL.csproj
  src/Moryx.Model/Moryx.Model.csproj
  src/Moryx.Runtime.DbUpdate/Moryx.Runtime.DbUpdate.csproj
  src/Moryx.Runtime.Kernel/Moryx.Runtime.Kernel.csproj
  src/Moryx.Runtime.Maintenance/Moryx.Runtime.Maintenance.csproj
  src/Moryx.Runtime.SmokeTest/Moryx.Runtime.SmokeTest.csproj
  src/Moryx.Runtime.Wcf/Moryx.Runtime.Wcf.csproj
  src/Moryx.Runtime.WinService/Moryx.Runtime.WinService.csproj
  src/Moryx.Runtime/Moryx.Runtime.csproj
  src/Moryx.TestTools.SystemTest/Moryx.TestTools.SystemTest.csproj
  src/Moryx.TestTools.UnitTest/Moryx.TestTools.UnitTest.csproj
  src/Moryx.Tools.Wcf/Moryx.Tools.Wcf.csproj
  src/Moryx/Moryx.csproj
Labels: documentation, enhancement

#97 Return to a filename compatible format
  VERSION
  src/Moryx/Tools/CrashHandler.cs
Labels: bug

#99 References tool returns empty array for null references
  src/Moryx/Tools/ReferenceGroup.cs
  src/Tests/Moryx.Tests/Extensions/ReflectionToolTests.cs
Labels: bug
