Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2022-09, with the labels that each got.

#161 Create migration guide
  docs/migrations/v3_to_v4.md
Labels: documentation

#170 New branch fixed maintenance Css
  src/Moryx.Maintenance.Web/package.json
  src/Moryx.Maintenance.Web/src/common/scss/maintenance.scss
  src/Moryx.Maintenance.Web/tslint.json
  src/Moryx.Maintenance.Web/webpack.config.js
Labels: bug

#171 Add attribute to export event stream
  src/Moryx.Asp.Extensions/ModuleEventStreamAttribute.cs
Labels: enhancement
