Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2023-02, with the labels that each got.

#219 Add method to UOW in order to link entities to business objects
  docs/articles/Core/DataModel/UnitOfWorkPattern.md
  src/Moryx.Model/EntityBase.cs
  src/Moryx.Model/EntityIdListener.cs
  src/Moryx.Model/Extensions/DbSetExtensions.cs
  src/Moryx.Model/Extensions/UnitOfWorkExtensions.cs
  src/Moryx.Model/IEntity.cs
  src/Moryx.Model/Repositories/IUnitOfWork.cs
  src/Moryx.Model/Repositories/UnitOfWork.cs
  src/Moryx.Products.Management/Implementation/RecipeStorage.cs
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
Labels: enhancement

#221 Fix entity id link in products and resources modules
  src/Moryx.Model/Extensions/UnitOfWorkExtensions.cs
  src/Moryx.Model/Repositories/UnitOfWork.cs
  src/Moryx.Products.Management/Implementation/Storage/ProductStorage.cs
  src/Moryx.Resources.Management/Resources/ResourceEntityAccessor.cs
  src/Moryx.Resources.Management/Resources/ResourceLinker.cs
  src/Moryx.Resources.Management/Resources/ResourceManager.cs
  src/Tests/Moryx.Resources.Management.Tests/ResourceEntityAccessorTests.cs
Labels: bug, data-model

#213 Feature/multi database support
  Core.sln
  Directory.Build.targets
  docs/tutorials/DataModel/CodeFirst.md
  src/Moryx.CommandCenter.Web/package.json
  src/Moryx.CommandCenter.Web/src/common/api/RestClientBase.ts
  src/Moryx.CommandCenter.Web/src/common/scss/maintenance.scss
  src/Moryx.CommandCenter.Web/src/databases/api/DatabasesRestClient.ts
  src/Moryx.CommandCenter.Web/src/databases/container/DatabaseModel.tsx
  src/Moryx.CommandCenter.Web/src/databases/container/Databases.tsx
  src/Moryx.CommandCenter.Web/src/databases/models/DataModel.ts
  src/Moryx.CommandCenter.Web/src/databases/models/DatabaseConfigModel.ts
  src/Moryx.CommandCenter.Web/src/databases/models/DatabaseConfigOptionModel.ts
  src/Moryx.CommandCenter.Web/src/databases/models/DatabaseConfigOptionPropertyModel.ts
  src/Moryx.CommandCenter.Web/src/databases/models/DatabasesResponse.ts
  src/Moryx.CommandCenter.Web/src/databases/models/TestConnectionResult.ts
  src/Moryx.CommandCenter.Web/src/modules/components/ConfigEditor/ConfigEditor.tsx
  src/Moryx.CommandCenter.Web/src/modules/models/Entry.ts
  src/Moryx.Model.InMemory/InMemoryDbContextManager.cs
  src/Moryx.Model.PostgreSQL/NpgsqlDatabaseConfig.cs
  src/Moryx.Model.PostgreSQL/NpgsqlModelConfigurator.cs
  src/Moryx.Model.Sqlite/Moryx.Model.Sqlite.csproj
  src/Moryx.Model.Sqlite/SqliteDatabaseConfig.cs
  src/Moryx.Model.Sqlite/SqliteDbContextManager.cs
  src/Moryx.Model.Sqlite/SqliteModelConfigurator.cs
  src/Moryx.Model/Attributes/ModelConfiguratorAttribute.cs
  src/Moryx.Model/Attributes/PossibleConfiguratorsAttribute.cs
  src/Moryx.Model/Configuration/IDatabaseConfig.cs
  src/Moryx.Model/Configuration/ModelConfiguratorBase.cs
  src/Moryx.Model/Configuration/NullModelConfigurator.cs
  src/Moryx.Model/DatabaseConfig.cs
  src/Moryx.Model/DatabaseConnectionSettings.cs
  src/Moryx.Model/DbContextManager.cs
  src/Moryx.Model/IDbContextManager.cs
  src/Moryx.Model/ModelServiceCollectionExtension.cs
  src/Moryx.Products.Model/ProductsContext.cs
  src/Moryx.Resources.Management/Model/ResourcesContext.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/DatabaseController.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Exceptions/Exceptions.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Models/DataModel.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Models/DatabaseConfigModel.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Models/DatabaseConfigOptionModel.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Response/DatabasesResponse.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Services/DatabaseConfigUpdateService.cs
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/Services/IDatabaseConfigUpdateService.cs
  src/Moryx.Runtime.Kernel/Configuration/ConfigManager.cs
  src/Moryx.TestTools.Test.Model/TestModelContext.cs
  src/StartProject.Asp/Program.cs
  src/StartProject.Asp/StartProject.Asp.csproj
  src/Tests/Moryx.Products.IntegrationTests/Moryx.Products.IntegrationTests.csproj
  src/Tests/Moryx.Runtime.Endpoints.Tests/Databases/UpdateConfigSqliteTests.cs
  src/Tests/Moryx.Runtime.Endpoints.Tests/Moryx.Runtime.Endpoints.Tests.csproj
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleManagerTests.cs
Labels: enhancement

#224 Adjust default SQLite connection string to prevent db files being cre…
  src/Moryx.Model.Sqlite/SqliteDatabaseConfig.cs
  src/Moryx.Model.Sqlite/SqliteModelConfigurator.cs
Labels: enhancement

#225 Rename Maintenance files to CommandCenter
  MORYX-Framework.sln
  docs/manual/commandcenter.md
  src/Moryx.CommandCenter.Web/Pages/CommandCenter.cshtml
  src/Moryx.CommandCenter.Web/Pages/CommandCenter.cshtml.cs
  src/Moryx.CommandCenter.Web/package.json
  src/Moryx.CommandCenter.Web/src/common/container/App.tsx
  src/Moryx.CommandCenter.Web/src/common/scss/commandcenter.scss
  src/Moryx.Maintenance.Web/package-lock.json
  src/Moryx.Maintenance.Web/wwwroot/bundle.js
  src/StartProject.Asp/Pages/Index.cshtml
  src/StartProject.Asp/Pages/Index.cshtml.cs
  src/StartProject.Asp/Properties/launchSettings.json
Labels: invalid

#226 Split database contexts into general and database specific contexts
  src/Moryx.Model.PostgreSQL/Attributes/NpgsqlDatabaseContextAttribute.cs
  src/Moryx.Model.PostgreSQL/NpgsqlModelConfigurator.cs
  src/Moryx.Model.Sqlite/Attributes/SqliteContextAttribute.cs
  src/Moryx.Model.Sqlite/SqliteModelConfigurator.cs
  src/Moryx.Model/Attributes/SqliteContextAttribute.cs
  src/Moryx.Model/Configuration/ModelConfiguratorBase.cs
  src/Moryx.Model/Configuration/NullModelConfigurator.cs
  src/Moryx.Model/DbContextManager.cs
  src/Moryx.Model/IModelConfigurator.cs
  src/Moryx.Products.Model/Migrations/Npgsql/20220906133824_InitialCreate.Designer.cs
  src/Moryx.Products.Model/Migrations/Npgsql/20220906133824_InitialCreate.cs
  src/Moryx.Products.Model/Migrations/Npgsql/ProductsContextModelSnapshot.cs
  src/Moryx.Products.Model/Migrations/Sqlite/20230214165158_InitialCreate.Designer.cs
  src/Moryx.Products.Model/Migrations/Sqlite/20230214165158_InitialCreate.cs
  src/Moryx.Products.Model/Migrations/Sqlite/SqliteProductsContextModelSnapshot.cs
  src/Moryx.Products.Model/Moryx.Products.Model.csproj
  src/Moryx.Products.Model/NpgsqlProductsContext.cs
  src/Moryx.Products.Model/ProductsContext.cs
  src/Moryx.Products.Model/SqliteProductsContext.cs
  src/Moryx.Resources.Management/Model/Migrations/Npgsql/20211104134830_InitialCreate.Designer.cs
  src/Moryx.Resources.Management/Model/Migrations/Npgsql/20211104134830_InitialCreate.cs
  src/Moryx.Resources.Management/Model/Migrations/Npgsql/ResourcesContextModelSnapshot.cs
  src/Moryx.Resources.Management/Model/Migrations/Sqlite/20230215071938_InitialCreate.Designer.cs
  src/Moryx.Resources.Management/Model/Migrations/Sqlite/20230215071938_InitialCreate.cs
  src/Moryx.Resources.Management/Model/Migrations/Sqlite/SqliteResourcesContextModelSnapshot.cs
  src/Moryx.Resources.Management/Model/NpgsqlResourcesContext.cs
  src/Moryx.Resources.Management/Model/ResourcesContext.cs
  src/Moryx.Resources.Management/Model/SqliteResourcesContext.cs
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
Labels: data-model

#227 Added reusable workflow and dependant packages with coverage feature
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  src/Tests/Moryx.AbstractionLayer.Tests/Moryx.AbstractionLayer.Tests.csproj
  src/Tests/Moryx.Container.Tests/Moryx.Container.Tests.csproj
  src/Tests/Moryx.Model.Tests/Moryx.Model.Tests.csproj
  src/Tests/Moryx.Notifications.Tests/Moryx.Notifications.Tests.csproj
  src/Tests/Moryx.Products.Management.Tests/Moryx.AbstractionLayer.Products.Endpoints.Tests.csproj
  src/Tests/Moryx.Resources.Management.Tests/Moryx.Resources.Management.Tests.csproj
  src/Tests/Moryx.Runtime.Endpoints.Tests/Moryx.Runtime.Endpoints.Tests.csproj
  src/Tests/Moryx.Runtime.Kernel.Tests/Moryx.Runtime.Kernel.Tests.csproj
  src/Tests/Moryx.Runtime.Tests/Moryx.Runtime.Tests.csproj
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
Labels: enhancement

#228 Added obsolete for old signin way
  src/Moryx/Modules/ModuleMenuCategory.cs
Labels: enhancement
