Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2023-01, with the labels that each got.

#204 Fixed scrollbar
  src/Moryx.Maintenance.Web/Pages/Maintenance.cshtml
  src/Moryx.Maintenance.Web/src/common/scss/maintenance.scss
Labels: enhancement

#208 Added confirmation dialog to database delete action
  src/Moryx.Maintenance.Web/src/databases/container/DatabaseModel.tsx
Labels: enhancement

#212 Added instructions for logging in asp-net core
  docs/tutorials/Log4Net.md
Labels: documentation

#217 Add Platform intialization to service collection extensions
  docs/migrations/v5_to_v6.md
  src/Moryx.Runtime.Kernel/KernelServiceCollectionExtensions.cs
  src/Moryx.Runtime/RuntimePlatform.cs
  src/Moryx/Platform.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/KernelServiceCollectionExtensionsTests.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleManagerTests.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/IFacadeA.cs
  src/Tests/Moryx.Runtime.Kernel.Tests/ModuleMocks/ServerModuleA.cs
Labels: bug
