Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2024-11, with the labels that each got.

#482 Add propper 400 response to update and save actions in the resource controller
  src/Moryx.AbstractionLayer.Resources.Endpoints/ResourceManagementController.cs
  src/Moryx/Serialization/DefaultSerialization.cs
Labels: bug

#483 Allow DeadEndValidator to pass on workplans with disconnected connectors
  src/Moryx/Workflows/Validation/DeadEndValidator.cs
Labels: bug

#476 Fix exception on creating a bidirectional link to a new resource
  src/Moryx.AbstractionLayer.Resources.Endpoints/Converter/ResourceToModelConverter.cs
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
  src/Moryx.Resources.Management/Resources/ResourceEntityAccessor.cs
  src/Moryx.Resources.Management/Resources/ResourceLinker.cs
  src/Tests/Moryx.Resources.Management.Tests/Mocks/ReferenceResource.cs
  src/Tests/Moryx.Resources.Management.Tests/ResourceLinkerTests.cs
Labels: bug

#484 Port: Add propper 400 response to update and save actions in the resource controller
  src/Moryx.AbstractionLayer.Resources.Endpoints/ResourceManagementController.cs
  src/Moryx/Serialization/DefaultSerialization.cs
Labels: bug

#488 Port: Allow DeadEndValidator to pass on workplans with disconnected connectors
  src/Moryx/Workflows/Validation/DeadEndValidator.cs
Labels: bug

#486 Port: Fix exception on creating a bidirectional link to a new resource
  src/Moryx.AbstractionLayer.Resources.Endpoints/Converter/ResourceToModelConverter.cs
  src/Moryx.Resources.Management/Moryx.Resources.Management.csproj
  src/Moryx.Resources.Management/Resources/ResourceEntityAccessor.cs
  src/Moryx.Resources.Management/Resources/ResourceLinker.cs
  src/Tests/Moryx.Resources.Management.Tests/Mocks/ReferenceResource.cs
  src/Tests/Moryx.Resources.Management.Tests/ResourceLinkerTests.cs
Labels: bug

#491 Navigate to `modules` by default
  src/Moryx.CommandCenter.Web/src/common/container/App.tsx
Labels: bug, enhancement

#493 Fix test steps in build pipeline
  .build/BuildToolkit.ps1
  .github/workflows/build-and-test.yml
  Directory.Build.targets
  src/Tests/Moryx.Communication.Sockets.IntegrationTests/Moryx.Communication.Sockets.IntegrationTests.csproj
  src/Tests/Moryx.Container.Tests/Moryx.Container.Tests.csproj
  src/Tests/Moryx.Runtime.Kernel.Tests/Moryx.Runtime.Kernel.Tests.csproj
  src/Tests/Moryx.Runtime.SystemTests/Moryx.Runtime.SystemTests.csproj
  src/Tests/Moryx.Runtime.Tests/Moryx.Runtime.Tests.csproj
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
  src/Tests/Moryx.Tools.Wcf.SystemTests/Moryx.Tools.Wcf.SystemTests.csproj
Labels: pipeline

#487 Add `FunctionResult<TResult>` to allow functions return 'proper' results
  src/Moryx/Tools/FunctionResult.cs
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
  src/Tests/Moryx.Tests/Tools/FunctionResultTestsBase.cs
  src/Tests/Moryx.Tests/Tools/FunctionResultWithNothingTests.cs
  src/Tests/Moryx.Tests/Tools/FunctionResultWithTypeTests.cs
Labels: enhancement

#497 Port: Add `FunctionResult<TResult>` to allow functions return 'proper' results
  src/Moryx/Tools/FunctionResult.cs
  src/Tests/Moryx.Tests/Moryx.Tests.csproj
  src/Tests/Moryx.Tests/Tools/FunctionResultTestsBase.cs
  src/Tests/Moryx.Tests/Tools/FunctionResultWithNothingTests.cs
  src/Tests/Moryx.Tests/Tools/FunctionResultWithTypeTests.cs
Labels: enhancement
