Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2025-09, with the labels that each got.

#590 Bulma is not used as a lib in the Launcher anymore
  src/Moryx.Launcher/Pages/Shared/_Layout.cshtml
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma-rtl.css
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma-rtl.css.map
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma-rtl.min.css
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma.css
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma.css.map
  src/Moryx.Launcher/wwwroot/lib/bulma/css/bulma.min.css
Labels: enhancement, npm, dependencies

#594 Port thread-safe-schedule-execution to release 6
  src/Moryx/Threading/ParallelOperations.cs
Labels: port

#596 Port: Fix AvailableCapabilitiesAttribute to handle ambiguous capabilities
  src/Moryx.AbstractionLayer/Resources/Attributes/AvailableCapabilitiesAttribute.cs
  src/Tests/Moryx.AbstractionLayer.Tests/CapabilitiesTests.cs
  src/Tests/Moryx.AbstractionLayer.Tests/TestData/NamespaceA/SameNameCapabilities.cs
  src/Tests/Moryx.AbstractionLayer.Tests/TestData/NamespaceB/SameNameCapabilities.cs
Labels: bug, port

#593 Fix case sensitive enum serialization
  src/Moryx.CommandCenter.Web/src/dashboard/components/HealthStateBadge.tsx
  src/Moryx.CommandCenter.Web/src/databases/container/DatabaseModel.tsx
  src/Moryx.CommandCenter.Web/src/modules/converter/EnumTypeHelper.ts
Labels: bug

#598 Port: Do not ValidateHealthState for response of published notifications
  src/Moryx.Notifications/Facade/NotificationSourceFacade.cs
Labels: bug, port

#613 Fix case sensitive enum serialization
  src/Moryx.CommandCenter.Web/src/dashboard/components/HealthStateBadge.tsx
  src/Moryx.CommandCenter.Web/src/databases/container/DatabaseModel.tsx
  src/Moryx.CommandCenter.Web/src/modules/converter/EnumTypeHelper.ts
Labels: bug, port

#601 Port: FIX: Allow numbers in TextBindingResolver
  src/Moryx/Bindings/TextBindingResolverFactory.cs
Labels: bug, port

#614 Port: Do not ValidateHealthState for response of published notifications
  src/Moryx.Notifications/Facade/NotificationSourceFacade.cs
  src/Moryx/Serialization/EntryConvert/EntryConvert.cs
  src/Tests/Moryx.Tests/Serialization/DummyClass.cs
  src/Tests/Moryx.Tests/Serialization/SerializationTests.cs
Labels: bug, port

#616 Add support for stateBaseType
  src/Moryx/StateMachines/StateBase.cs
  src/Moryx/StateMachines/StateMachine.cs
Labels: enhancement

#638 Port: Html reader for worker support to future
  src/Moryx.ControlSystem.WorkerSupport.Web/src/app/components/media-contents/media-contents.component.html
  src/Moryx.ControlSystem.WorkerSupport.Web/src/app/components/media-contents/media-contents.component.ts
  src/Moryx.ControlSystem.WorkerSupport.Web/src/app/components/worker-instructions/worker-instructions.component.html
  src/Moryx.ControlSystem.WorkerSupport.Web/src/app/services/instruction-state.service.ts
  src/Moryx.ControlSystem.WorkerSupport.Web/src/app/services/instruction.service.ts
Labels: enhancement, port

#639 Port: Fix border issue with Angular Material inputs
  src/Moryx.Launcher/wwwroot/css/app.css
Labels: bug, port

#634 Fix invalidation of refresh tokens
  src/Moryx.Identity.AccessManagement/Identity/TokenService.cs
Labels: enhancement, port

#635 Fix concurrency exception
  src/Moryx.Identity.AccessManagement/Controllers/API/EntraIdAuthController.cs
Labels: bug, port

#648 Port: Add automatic support for Inputs to the VisualInstructionParameters
  docs/migrations/v8_to_v10.md
  src/Moryx.Benchmarking/BenchmarkParameters.cs
  src/Moryx.ControlSystem/VisualInstructions/VisualInstruction.cs
  src/Moryx.ControlSystem/VisualInstructions/VisualInstructionParameters.cs
  src/Moryx.ControlSystem/VisualInstructions/VisualInstructorExtensions.cs
Labels: enhancement, port

#641 Port/conditional-layout-to-future
  src/Moryx.Launcher/Pages/Shared/_Layout.cshtml
Labels: enhancement, port
