Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2025-04, with the labels that each got.

#534 Removed the encapsulation of ActionResult on return
  src/Moryx.AbstractionLayer.Resources.Endpoints/ResourceManagementController.cs
Labels: bug

#536 Removed resource initialiers from ModuleConfig
  src/Moryx.AbstractionLayer/Resources/IResourceManagement.cs
  src/Moryx.Resources.Management/ModuleController/ModuleConfig.cs
  src/Moryx.Resources.Management/ModuleController/ModuleConsole.cs
Labels: enhancement

#537 Updated references and fixed typos
  docs/articles/AbstractionLayer.md
  docs/articles/Processing/Activities.md
  docs/articles/Processing/Workplans.md
  docs/articles/Resources/Overview.md
  docs/articles/Resources/Types/DriverResource.md
  docs/articles/Resources/Types/Overview.md
Labels: documentation, duplicate
