Repository PHOENIXCONTACT/MORYX-Framework, pull requests merged in 2025-02, with the labels that each got.

#519 Using Path.Combine for creating backup-path in DatabaseController
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/DatabaseController.cs
Labels: bug

#520 Port: Using Path.Combine for creating backup-path in DatabaseController
  src/Moryx.Runtime.Endpoints/Databases/Endpoint/DatabaseController.cs
Labels: bug

#521 File name ReferenceCollectionMock was not matching class name
  src/Moryx.AbstractionLayer.TestTools/ReferenceCollectionMock.cs
Labels: enhancement

#523 Port: Fix NullReferenceException in internal Proxify extension.
  src/Moryx.Resources.Management/Facades/ResourceManagementFacade.cs
Labels: bug

#527 Fixed documentation about StateMachine initialization
  docs/articles/DesignPatterns.md
Labels: documentation
